spring:
  datasource:
    url: jdbc:h2:mem:educationalDatabase
    driver-class-name: org.h2.Driver
    username: admin
    password: admin
  sql:
    init:
      mode: never
  jpa:
    open-in-view: false
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  cache:
    cache-names:
      - applicationAclCache
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
logging:
  level:
    org:
      springframework:
        security: TRACE
