spring:
  datasource:
    url: jdbc:h2:mem:educationalDatabase
    driverClassName: org.h2.Driver
    username: root
    password: root
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  liquibase:
    enabled: true
    changeLog: classpath:db/changelog/db.changelog-master.yaml
