spring:
  shell:
    interactive:
      enabled: true
    noninteractive:
      enabled: false
    command:
      version:
        enabled: false
  data:
    mongodb:
      port: 8099
      database: db

de:
  flapdoodle:
    mongodb:
      embedded:
        version: 4.0.2

mongock:
  runner-type: "InitializingBean"
  change-logs-scan-package: ru.otus.hw.mongock.test.changelog
  mongo-db:
    write-concern:
      journal: false
    read-concern: local
